Use release version of PyImageJ in rtd builds
Readthedocs still fails to build with error:

ERROR: Directory '../../../' is not installable.
Neither 'setup.py' nor 'pyproject.toml' found.

This indicates that pip is not running from the
doc/rtd/source folder as I assumed. For now
let's use the release version of PyImageJ
from PyPi. This "should" build fine.