Fix bug when running without ImageJ Legacy
We must always guard against jc.ImagePlus and
other original ImageJ classes being None.

Avoids the error:
  TypeError: isinstance() arg 2 must be a type, a tuple of types, or a union

which happens when calling:
  isinstance(obj, None)