Remove @property from Java class accessors
The direct property access doesn't work, because invocations such as:

  isinstance(data, _ImagePlus):

fail with:

  TypeError: isinstance() arg 2 must be a type, a tuple of types, or a union

and so the purpose of declaring these functions as properties is utterly
defeated. We may as well just make them regular functions and call them
accordingly, since it's shorter.