Add imagej launch script
This console-based entry point runs a new imagej_main method.
Unfortunately, there is an issue where pyjnius cannot convert the
Python args into a Java String[] for use with ij.launch(args):

  Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
    File ".../pyimagej/imagej/imagej.py", line 201, in imagej_main
      ij.launch(args)
    File "jnius/jnius_export_class.pxi", line 728, in jnius.JavaMethod.__call__
    File "jnius/jnius_conversion.pxi", line 107, in jnius.populate_args
    File "jnius/jnius_conversion.pxi", line 627, in jnius.convert_pyarray_to_java
  jnius.JavaException: Invalid variable used for L array

Quick attempts to convert from the Python args (a tuple) to Java String[]
through various means failed. Need to investigate more deeply later.

Closes #15.